<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by extdeveval.
// This file was generated on 2010-02-01 20:41

$extensionClassesPath = t3lib_extMgm::extPath('gg_ch') . 'Classes/';
return array(
	'tx_ggch_helpers_coordinates' => $extensionClassesPath . 'Helpers/Coordinates.php',
	'tx_ggch_helpers_dxfreader' => $extensionClassesPath . 'Helpers/DxfReader.php',
);
?>